# Generated by Django 6.0.4 on 2026-04-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_create_admin'),
        ('appointments', '0004_seed_full_doctors'),
    ]

    operations = [
    ]
